language: node_js
node_js:
- '4.3'
deploy:
  provider: npm
  email: miyoda@gmail.com
  api_key:
    secure: mlqyf+sNezO+Hg7V9Gb/8ZAfnSKd9BiqYmzoVKPqq41fGE8c/e4uHnv8576lqN87+NRxkCaIjG8MnHOa5xnY+WKOkzDhWLWFewjGL82yrmmHRRT5pvBYOU+7rfo3yyqAUVFzpLDdKZql9P86IHgN8mAo9lMxUs3j5vB3AuuKxg1dQoS0SwYG+sS6OpDELYgGtygZtzk1AXoNS/+eax7YTS2jlPUhkukWv7VrRNuKoK2HIodzBXwL8ujA5DAFMcCKyk9lHMhnJbFbyP9PqO5T8J9Q1zZ68VYPjbaPjUEpjBvhy8B/bO/w4KQUJZTbGx8oEyRYgEAI+oVmlAZk2inprm8Y9X14Hq4GW99qUFHRU2tcDJEMu+sXdguGjVZTsIyu9BHrhQixNP/YNa2ry/SLD+jVOxUDQ6sxPPrWECumYdJp5whoC+DbA0wNVnQxSedl3yneAU3wZyAC2yCaTqmDfs/9HfItCKJQGWng4xBhfQpZPZFDizZPvrW6FnUsQBQPtno20L91xjpf2FKXiG5D5WmHOqM35HFUkX0NC53XtlP4qLSziJ8JXZhTM2Bq41hVjitb3w42Z1//PwTrj/AhRgeD7uPv4oip2W4rouh+3ZYlDHtzwwQ9wi7wJTJaKOjto6QKomlP3VDCu/myADPfZdeHsRBY4AWT5T/InTg4InE=
  on:
    tags: true
    repo: miyoda/swagger-utils
notifications:
  email: false
  slack:
    on_success: always
    on_failure: always
